[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
cryptofantasy = "7QHMrTeoLTggAy11kTTEwtoRzcvK8rEeY1TRu4oUdgGP"

[programs.localnet]
cryptofantasy = "7QHMrTeoLTggAy11kTTEwtoRzcvK8rEeY1TRu4oUdgGP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=0ef6f1af-3077-456d-8df0-21e8b74a9382"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/cryptofantasy"
]

[test]
startup_wait = 30000